#!/usr/bin/env python3
"""Generate human- and machine-readable indexes from skill metadata."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
CATEGORIES = ("common", "personal", "meta")
REQUIRED = (
    "name",
    "description",
    "category",
    "subject",
    "scope",
    "status",
    "version",
    "invocation",
)
ENUMS = {
    "category": set(CATEGORIES),
    "scope": {"universal", "personal", "repository"},
    "status": {"draft", "experimental", "stable", "deprecated"},
    "invocation": {"user", "model", "both"},
}
REGISTRY_SCHEMA_VERSION = 3
NAME_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
VERSION_RE = re.compile(r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$")


def parse_frontmatter(path: Path) -> dict[str, object]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n") or "\n---\n" not in text[4:]:
        raise ValueError(f"missing YAML frontmatter: {path.relative_to(ROOT)}")
    end = text.index("\n---\n", 4)
    values: dict[str, object] = {}
    for line in text[4:end].splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if ":" not in line:
            raise ValueError(f"invalid frontmatter line in {path.relative_to(ROOT)}: {line}")
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip().strip('"\'')
        if key == "requires":
            if not (value.startswith("[") and value.endswith("]")):
                raise ValueError(
                    f"requires must be an inline list in {path.relative_to(ROOT)}"
                )
            items = [item.strip().strip('"\'') for item in value[1:-1].split(",") if item.strip()]
            values[key] = items
        else:
            values[key] = value
    return values


def collect() -> list[dict[str, str]]:
    records: list[dict[str, str]] = []
    ids: set[str] = set()
    for category in CATEGORIES:
        for skill_file in sorted((ROOT / category).rglob("SKILL.md")):
            relative = skill_file.relative_to(ROOT)
            metadata = parse_frontmatter(skill_file)
            missing = [field for field in REQUIRED if not metadata.get(field)]
            if missing:
                raise ValueError(f"missing metadata in {relative}: {', '.join(missing)}")
            skill_dir = skill_file.parent.name
            skill_id = skill_file.parent.relative_to(ROOT).as_posix()
            if not NAME_RE.fullmatch(metadata["name"]):
                raise ValueError(f"invalid skill name in {relative}: {metadata['name']}")
            if metadata["name"] != skill_dir:
                raise ValueError(f"name does not match directory in {relative}")
            if metadata["category"] != category:
                raise ValueError(f"category does not match path in {relative}")
            for field, allowed in ENUMS.items():
                if metadata[field] not in allowed:
                    raise ValueError(f"invalid {field} in {relative}: {metadata[field]}")
            if not isinstance(metadata["version"], str) or not VERSION_RE.fullmatch(metadata["version"]):
                raise ValueError(f"invalid version in {relative}: {metadata['version']}")
            requires = metadata.get("requires", [])
            if not isinstance(requires, list) or any(
                not isinstance(item, str) or "/" not in item for item in requires
            ):
                raise ValueError(f"invalid requires in {relative}: {requires}")
            if skill_id in ids:
                raise ValueError(f"duplicate skill id: {skill_id}")
            ids.add(skill_id)
            records.append(
                {
                    "id": skill_id,
                    "name": metadata["name"],
                    "description": metadata["description"],
                    "category": metadata["category"],
                    "subject": metadata["subject"],
                    "scope": metadata["scope"],
                    "status": metadata["status"],
                    "version": metadata["version"],
                    "invocation": metadata["invocation"],
                    "path": relative.as_posix(),
                    "requires": requires,
                }
            )
    return sorted(records, key=lambda item: (item["category"], item["subject"], item["name"]))


def render_markdown(records: list[dict[str, str]]) -> str:
    lines = [
        "# Skill index",
        "",
        "> Generated by `scripts/generate_skill_index.py`; do not edit manually.",
        "",
        f"Total skills: **{len(records)}**",
        "",
        "| ID | Description | Scope | Status | Version | Invocation | Requires | Path |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for item in records:
        description = item["description"].replace("|", "\\|")
        requires = ", ".join(f"`{value}`" for value in item["requires"]) or "—"
        lines.append(
            f"| `{item['id']}` | {description} | `{item['scope']}` | `{item['status']}` | `{item['version']}` | `{item['invocation']}` | {requires} | `{item['path']}` |"
        )
    return "\n".join(lines) + "\n"


def render_json(records: list[dict[str, str]]) -> str:
    return json.dumps(
        {"schema_version": REGISTRY_SCHEMA_VERSION, "skills": records},
        indent=2,
        ensure_ascii=False,
    ) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when generated files are stale")
    args = parser.parse_args()
    try:
        records = collect()
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    outputs = {
        ROOT / "docs/skill-index.md": render_markdown(records),
        ROOT / "data/skills.json": render_json(records),
    }
    stale = False
    for path, content in outputs.items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                print(f"stale generated file: {path.relative_to(ROOT)}")
                stale = True
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"generated {path.relative_to(ROOT)}")
    return 1 if stale else 0


if __name__ == "__main__":
    raise SystemExit(main())
